[project]
name = "special-data-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanghyuk07a-cpu", email = "sanghyuk07a@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[project.scripts]
special-data-lab = "special_data_lab:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
